
const DEMO={seller:{email:"seller@demo.com",pass:"12345",role:"seller",name:"Seller Demo"},customer:{email:"customer@demo.com",pass:"12345",role:"customer",name:"Customer Demo"}};
function setUser(u){localStorage.setItem("kisht_user",JSON.stringify(u))}
function getUser(){const s=localStorage.getItem("kisht_user");try{return s?JSON.parse(s):null}catch(e){return null}}
function signOut(){localStorage.removeItem("kisht_user");window.location.href="index.html"}
function submitLogin(e){e.preventDefault();const role=document.querySelector("#role").value;const email=document.querySelector("#email").value.trim();const pass=document.querySelector("#password").value.trim();const exp=role==="seller"?DEMO.seller:DEMO.customer;const ok=(email===exp.email&&pass===exp.pass);const hint=document.querySelector("#hint");if(ok){setUser(exp);window.location.href="dashboard.html"}else{hint.textContent="Invalid credentials. Try demo: "+exp.email+" / 12345";hint.classList.remove("hidden")}}
function guard(){const u=getUser();if(!u){window.location.href="index.html";return}document.querySelectorAll(".userName").forEach(el=>el.textContent=u.name);document.querySelectorAll(".userRole").forEach(el=>el.textContent=u.role)}
function calcEMI(){const p=parseFloat(document.querySelector("#p").value||0);const r=parseFloat(document.querySelector("#r").value||0)/12/100;const n=parseInt(document.querySelector("#n").value||0);const out=document.querySelector("#emiOut");if(p<=0||r<=0||n<=0){out.textContent="Enter valid amount, rate, months.";return}const emi=p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);out.textContent="₹ "+emi.toFixed(2)+" / month"}
function addLoanRow(){const name=document.querySelector("#loanName").value.trim();const amt=document.querySelector("#loanAmt").value.trim();if(!name||!amt)return;const t=document.querySelector("#loanBody");const tr=document.createElement("tr");tr.innerHTML=`<td>${name}</td><td>₹ ${amt}</td><td><span class="badge">Active</span></td>`;t.appendChild(tr);document.querySelector("#loanName").value="";document.querySelector("#loanAmt").value=""}
function addReward(){const r=document.querySelector("#rewardPts");const val=parseInt(r.textContent||"0",10);r.textContent=val+10}
function convertBill(){const bill=parseFloat(document.querySelector("#billAmt").value||0);const months=parseInt(document.querySelector("#billMonths").value||0);const rate=16/12/100;const out=document.querySelector("#billOut");if(bill<=0||months<=0){out.textContent="Enter valid bill & months.";return}const emi=bill*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1);out.textContent=`Converted: ₹${bill.toFixed(2)} → EMI ₹${emi.toFixed(2)} x ${months} months`}
function closeLoan(){const id=document.querySelector("#closeId").value.trim();const out=document.querySelector("#closeOut");if(!id){out.textContent="Enter a loan/account id.";return}out.textContent="✅ Closure request submitted for "+id+" (demo)."}
function addProduct(){const name=document.querySelector("#prodName").value.trim();if(!name)return;const list=document.querySelector("#prodList");const li=document.createElement("li");li.textContent=name;list.appendChild(li);document.querySelector("#prodName").value=""}
function submitTicket(e){e.preventDefault();document.querySelector("#ticketOut").textContent="✅ Ticket submitted. Our team will reach out (demo)."}
